language: java

addons:
  ssh_known_hosts:
  - ftp.interlis.ch
  apt:
    packages:
    - python3
    - python3-pip

branches:
  only:
    - main
    - stable

install: true

before_script:
    - python3 --version
    - virtualenv -p python3 my_py3
    - source my_py3/bin/activate # to activate the python3 environemt    
    - python -m pip --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org install docutils
    - python -m pip --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org install Pygments
    - python -m pip freeze

script: 
  - ./gradlew -Drst2html=`which rst2html.py` usrdoc build 
deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew -Drepos_pwd=${repos_pwd} -Drepos_usr=jql_jars-INTE uploadArchives
    on:
      branch: main
  - provider: script
    skip_cleanup: true
    script: ./gradlew -Drepos_pwd=${repos_pwd} -Drepos_usr=jql_jars-INTE '-Drelease=' -Ddownloads_pwd=${downloads_pwd} -Ddownloads_usr=jql_downloads -Ddocs_pwd=${docs_pwd} -Ddocs_usr=jql_docs uploadArchives uploadBin uploadDoc
    on:
      branch: stable
